# Generated by Django 4.0.3 on 2022-04-03 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
